In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.

print(np.version.version)



#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.random((2,3,5))


#4. Print a.

print(a)

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b=np.ones((5,2,3))


#6. Print b.
print(b)
#7. Do a and b have the same size? How do you prove that in Python code?

print(a.size==b.size)


#8. Are you able to add a and b? Why or why not?

print(a.shape==b.shape) #no, porque porque no tienen las mismas dimensiones

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c=b.reshape((2,3,5))
print(c)


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d=a+c
print(d) #porque tienen mismo shape (mismas dimensiones)

1.16.0
[[[0.3540464  0.58876017 0.26721991 0.40722135 0.26301744]
  [0.74079708 0.74324577 0.74367292 0.71719077 0.90195517]
  [0.36553376 0.19043649 0.41134271 0.89909621 0.64124219]]

 [[0.98576623 0.30301562 0.7237828  0.69260952 0.17344713]
  [0.80734674 0.95929544 0.99421543 0.69918457 0.5357884 ]
  [0.28745848 0.38216693 0.65375687 0.47089961 0.97675872]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
True
False
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[1.3540464  1.58876017 1.26721991 1.40722135 1.26301744]
  [1.74079708 1.74324577 1.74367292 1.71719077 1.90195517]
  [1.36553376 1.19043649 1.41134271 1.89909621 1.64124219]]

 [[1.98576623 1.30301562 1.7237828  1.69260952 1.17344713]
  [1.80734674 1.95929544 1.99421543 1.69918457 1.5357884 ]
  [1.28745848 1.38216693 1.65375687 1.47089961 1.97675872]]]
